### ISSUE TITLE
Infinite loop when length is a multiple of 256

### ISSUE THREAD

**Issue by Scratch-net** [cmiceli/password-generator-go#1] opened 2018-11-02 18:15 UTC
If you call rand_char(32, ...) then the code will loop forever because maxrb will be 0

**Comment by cmiceli** [comment] 2018-11-03 01:33
Hi!

Thanks for the report. rand_char is not exported so I am curious to know how you are using the code. Just in case, I did test both NewPassword(512) and NewPassword(32).

If you have a working sample which shows this issue please let me know and I can work to fix it. I will keep the issue open for a week so you can get me the repro.

Thanks,
Chris.

**Comment by Scratch-net** [comment] 2018-11-03 04:08
Sorry, i was a bit wrong. If we will change the charset to a multiple of 256 it will loop:
```go
pwordgen.StdChars = []byte("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
fmt.Println(pwordgen.NewPassword(64))
```

pwordgen.StdChars = []byte("0123456789ABCDEF")
will also work

**Comment by Scratch-net** [comment] 2018-11-05 06:30
@cmiceli can you reproduce now?

**Comment by cmiceli** [comment] 2018-11-10 04:56
Sorry for not getting back sooner.

I have just updated this with a fix. The issue is that I want to make it return an error if the reading from rand.Reader fails, but that would involve a change in interface which I don't want to do. Let me know if this causes trouble for you and I can fix it.

The good news is that I now have a few tests for this. I've closed this but let me know if you find any other breakage.

**Closed as completed by cmiceli** 2018-11-10 04:56 UTC
Labels: bug
